jobs:
  build:
    defaults:
      run:
        working-directory: "."
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "24.7.0"
      - name: "Install the dependencies"
        run: |
          npm ci
      - name: "Build"
        run: |
          npm run build
      - name: "Upload artifact"
        uses: "actions/upload-pages-artifact@v3"
        with:
          name: "github-pages"
          path: "./build"
  deploy:
    environment:
      name: "github-pages"
    name: "Deploy"
    needs:
      - "build"
    runs-on: "ubuntu-latest"
    steps:
      - id: "deploy_to_github_pages"
        name: "Deploy to GitHub Pages"
        uses: "actions/deploy-pages@v4"
        with:
          artifact_name: "github-pages"
name: "Deploy to GitHub Pages"
on:
  workflow_dispatch:
